services:
  - type: web
    name: impact-score-back
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
